export const RECEIVE_SITES = "RECEIVE_SITES";
export const RECEIVE_SESSION = "RECEIVE_SESSION";
export const RECEIVE_LOGIN_RESPOND = "RECEIVE_LOGIN_RESPOND";
export const RECEIVE_SINGUP_RESPOND = "RECEIVE_SINGUP_RESPOND";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
